STATUS_DATA_AVAILABLE="Data fetched successfully"
STATUS_DATA_NOT_AVAILABLE="Data not available"
STATUS_RECORD_STORED="Record stored successfully"
STATUS_RECORD_NOT_STORED="Record could not be stored"
STATUS_RECORD_DELETED="Record deleted successfully"
STATUS_RECORD_NOT_DELETED="Record could not be deleted"